stages:
- name: Build
  steps:
  - runScriptConfig:
      image: bigrocs/golang-gcc:1.12
      shellScript: |-
        mkdir -p /go/src/github.com/gomsa
        ln -s `pwd` /go/src/github.com/gomsa/goods
        cd /go/src/github.com/gomsa/goods
        GO111MODULE=off
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o bin/service
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./rancher/Dockerfile
      buildContext: .
      tag: goods:${CICD_EXECUTION_SEQUENCE}
- name: Mariadb
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-mariadb
      version: 5.0.9
      answers:
        db.name: goods
        db.user: goods
        service.type: ClusterIP
        slave.replicas: "2"
      name: goods
      targetNamespace: srv
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml