kind: Service
apiVersion: v1
metadata:
  name: goods
  namespace: srv
spec:
  selector:
    app: goods
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      name: micro
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goods
  namespace: srv
  labels:
    app: goods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goods
  template:
    metadata:
      labels:
        app: goods
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
        - name: goods
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          command: [
            "service",
            "--selector=static",
            "--server_address=:8080",
          ]
          env:
            - name: DB_HOST
              value: "goods-mariadb"
            - name: DB_USER
              value: "goods"
            - name: DB_NAME
              value: "goods"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mariadb-password
                  name: goods-mariadb
          ports:
          - containerPort: 8080
            name: micro
            protocol: TCP
        - name: health
          image: microhq/health:kubernetes
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=goods",
            "--server_address=0.0.0.0:8080"
          ]
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
