// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/brand/brand.proto

package brand

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 数据库 Brands
type Brand struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo                 string   `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Brand) Reset()         { *m = Brand{} }
func (m *Brand) String() string { return proto.CompactTextString(m) }
func (*Brand) ProtoMessage()    {}
func (*Brand) Descriptor() ([]byte, []int) {
	return fileDescriptor_008f96e71eedc037, []int{0}
}

func (m *Brand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Brand.Unmarshal(m, b)
}
func (m *Brand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Brand.Marshal(b, m, deterministic)
}
func (m *Brand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Brand.Merge(m, src)
}
func (m *Brand) XXX_Size() int {
	return xxx_messageInfo_Brand.Size(m)
}
func (m *Brand) XXX_DiscardUnknown() {
	xxx_messageInfo_Brand.DiscardUnknown(m)
}

var xxx_messageInfo_Brand proto.InternalMessageInfo

func (m *Brand) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Brand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Brand) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Brand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Brand) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Brand) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ListQuery struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuery) Reset()         { *m = ListQuery{} }
func (m *ListQuery) String() string { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()    {}
func (*ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_008f96e71eedc037, []int{1}
}

func (m *ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuery.Unmarshal(m, b)
}
func (m *ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuery.Marshal(b, m, deterministic)
}
func (m *ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuery.Merge(m, src)
}
func (m *ListQuery) XXX_Size() int {
	return xxx_messageInfo_ListQuery.Size(m)
}
func (m *ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuery proto.InternalMessageInfo

func (m *ListQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListQuery) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListQuery) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

type Request struct {
	ListQuery            *ListQuery `protobuf:"bytes,1,opt,name=list_query,json=listQuery,proto3" json:"list_query,omitempty"`
	Brand                *Brand     `protobuf:"bytes,2,opt,name=Brand,proto3" json:"Brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_008f96e71eedc037, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetListQuery() *ListQuery {
	if m != nil {
		return m.ListQuery
	}
	return nil
}

func (m *Request) GetBrand() *Brand {
	if m != nil {
		return m.Brand
	}
	return nil
}

type Response struct {
	Brand                *Brand   `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Brands               []*Brand `protobuf:"bytes,2,rep,name=brands,proto3" json:"brands,omitempty"`
	Valid                bool     `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_008f96e71eedc037, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetBrand() *Brand {
	if m != nil {
		return m.Brand
	}
	return nil
}

func (m *Response) GetBrands() []*Brand {
	if m != nil {
		return m.Brands
	}
	return nil
}

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Brand)(nil), "brand.Brand")
	proto.RegisterType((*ListQuery)(nil), "brand.ListQuery")
	proto.RegisterType((*Request)(nil), "brand.Request")
	proto.RegisterType((*Response)(nil), "brand.Response")
}

func init() { proto.RegisterFile("proto/brand/brand.proto", fileDescriptor_008f96e71eedc037) }

var fileDescriptor_008f96e71eedc037 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0xb5, 0xed, 0x5a, 0xd7, 0x3b, 0x99, 0x12, 0x04, 0x8b, 0x20, 0x94, 0xe2, 0xc3, 0x44, 0xd8,
	0x60, 0x7e, 0xc1, 0xa6, 0x20, 0x82, 0x2f, 0x06, 0x7c, 0x75, 0x74, 0xcb, 0x65, 0x44, 0xba, 0xa6,
	0x6b, 0x32, 0xc1, 0xaf, 0xf1, 0xe7, 0xfc, 0x10, 0xc9, 0x4d, 0x36, 0x44, 0x5f, 0xfa, 0x52, 0xce,
	0x3d, 0xe7, 0xf4, 0xde, 0x73, 0x93, 0xc0, 0x45, 0xd3, 0x2a, 0xa3, 0x26, 0xcb, 0xb6, 0xac, 0x85,
	0xfb, 0x8e, 0x89, 0x61, 0x31, 0x15, 0xc5, 0x57, 0x00, 0xf1, 0xdc, 0x22, 0x36, 0x84, 0x50, 0x8a,
	0x2c, 0xc8, 0x83, 0x51, 0xc4, 0x43, 0x29, 0x18, 0x83, 0x5e, 0x5d, 0x6e, 0x30, 0x0b, 0xf3, 0x60,
	0x94, 0x72, 0xc2, 0x96, 0xab, 0xd4, 0x5a, 0x65, 0x91, 0xe3, 0x2c, 0x66, 0x39, 0x0c, 0x04, 0xea,
	0x55, 0x2b, 0x1b, 0x23, 0x55, 0x9d, 0xf5, 0x48, 0xfa, 0x4d, 0xb1, 0x2b, 0x80, 0x55, 0x8b, 0xa5,
	0x41, 0xb1, 0x28, 0x4d, 0x16, 0x93, 0x21, 0xf5, 0xcc, 0xcc, 0x58, 0x79, 0xd7, 0x88, 0xbd, 0x9c,
	0x38, 0xd9, 0x33, 0x33, 0x53, 0x3c, 0x41, 0xfa, 0x2c, 0xb5, 0x79, 0xd9, 0x61, 0xfb, 0xc9, 0xce,
	0x21, 0xae, 0xe4, 0x46, 0x1a, 0x9f, 0xd3, 0x15, 0x36, 0x56, 0x53, 0xae, 0x5d, 0xd4, 0x88, 0x13,
	0xb6, 0x9c, 0x56, 0xad, 0xd9, 0x47, 0xb5, 0xb8, 0x78, 0x83, 0x63, 0x8e, 0xdb, 0x1d, 0x6a, 0xc3,
	0x26, 0x00, 0x95, 0xd4, 0x66, 0xb1, 0xb5, 0x6d, 0xa9, 0xdb, 0x60, 0x7a, 0x36, 0x76, 0x07, 0x74,
	0x18, 0xc7, 0xd3, 0xea, 0x30, 0xb9, 0xf0, 0xe7, 0x44, 0x43, 0x06, 0xd3, 0x13, 0xef, 0x25, 0x8e,
	0x3b, 0xa9, 0x78, 0x87, 0x3e, 0x47, 0xdd, 0xa8, 0x5a, 0xa3, 0xf5, 0x93, 0xc3, 0xf7, 0xfe, 0xe3,
	0xa7, 0x82, 0x5d, 0x43, 0x42, 0x40, 0x67, 0x61, 0x1e, 0xfd, 0x33, 0x79, 0xcd, 0xee, 0xfc, 0x51,
	0x56, 0x52, 0xd0, 0x2a, 0x7d, 0xee, 0x8a, 0xe9, 0x77, 0x00, 0xc9, 0xdc, 0x19, 0x6e, 0xa0, 0x67,
	0x23, 0xb3, 0xa1, 0xff, 0xdd, 0xef, 0x78, 0x79, 0x7a, 0xa8, 0x5d, 0xa6, 0xe2, 0x88, 0x8d, 0x20,
	0x7a, 0xc4, 0x4e, 0xce, 0x5b, 0x48, 0xee, 0xe9, 0x8a, 0x3a, 0x9a, 0x5f, 0xe9, 0xc2, 0x3a, 0x9a,
	0x1f, 0xb0, 0xc2, 0x4e, 0xe6, 0x65, 0x42, 0xaf, 0xf5, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0xfb,
	0xf6, 0x4c, 0xbf, 0xc8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Brands service

type BrandsClient interface {
	// 获取品牌列表
	List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 根据 唯一 获取品牌信息
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 创建品牌
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 更新品牌
	Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 删除品牌
	Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type brandsClient struct {
	c           client.Client
	serviceName string
}

func NewBrandsClient(serviceName string, c client.Client) BrandsClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "brand"
	}
	return &brandsClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *brandsClient) List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Brands.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Brands.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Brands.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Brands.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Brands.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Brands service

type BrandsHandler interface {
	// 获取品牌列表
	List(context.Context, *Request, *Response) error
	// 根据 唯一 获取品牌信息
	Get(context.Context, *Request, *Response) error
	// 创建品牌
	Create(context.Context, *Request, *Response) error
	// 更新品牌
	Update(context.Context, *Request, *Response) error
	// 删除品牌
	Delete(context.Context, *Request, *Response) error
}

func RegisterBrandsHandler(s server.Server, hdlr BrandsHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Brands{hdlr}, opts...))
}

type Brands struct {
	BrandsHandler
}

func (h *Brands) List(ctx context.Context, in *Request, out *Response) error {
	return h.BrandsHandler.List(ctx, in, out)
}

func (h *Brands) Get(ctx context.Context, in *Request, out *Response) error {
	return h.BrandsHandler.Get(ctx, in, out)
}

func (h *Brands) Create(ctx context.Context, in *Request, out *Response) error {
	return h.BrandsHandler.Create(ctx, in, out)
}

func (h *Brands) Update(ctx context.Context, in *Request, out *Response) error {
	return h.BrandsHandler.Update(ctx, in, out)
}

func (h *Brands) Delete(ctx context.Context, in *Request, out *Response) error {
	return h.BrandsHandler.Delete(ctx, in, out)
}
