// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/taxcode/taxcode.proto

package taxcode

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 数据库 Taxcodes
type Taxcode struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent               int64    `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	IsParent             int64    `protobuf:"varint,3,opt,name=is_parent,json=isParent,proto3" json:"is_parent,omitempty"`
	Cess                 string   `protobuf:"bytes,4,opt,name=cess,proto3" json:"cess,omitempty"`
	DutyFree             string   `protobuf:"bytes,5,opt,name=duty_free,json=dutyFree,proto3" json:"duty_free,omitempty"`
	DutyFreeDesc         string   `protobuf:"bytes,6,opt,name=duty_free_desc,json=dutyFreeDesc,proto3" json:"duty_free_desc,omitempty"`
	Code                 int64    `protobuf:"varint,7,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Instruction          string   `protobuf:"bytes,9,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Keyword              string   `protobuf:"bytes,10,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Version              string   `protobuf:"bytes,11,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt            string   `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Taxcode) Reset()         { *m = Taxcode{} }
func (m *Taxcode) String() string { return proto.CompactTextString(m) }
func (*Taxcode) ProtoMessage()    {}
func (*Taxcode) Descriptor() ([]byte, []int) {
	return fileDescriptor_d78da315917493c0, []int{0}
}

func (m *Taxcode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Taxcode.Unmarshal(m, b)
}
func (m *Taxcode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Taxcode.Marshal(b, m, deterministic)
}
func (m *Taxcode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Taxcode.Merge(m, src)
}
func (m *Taxcode) XXX_Size() int {
	return xxx_messageInfo_Taxcode.Size(m)
}
func (m *Taxcode) XXX_DiscardUnknown() {
	xxx_messageInfo_Taxcode.DiscardUnknown(m)
}

var xxx_messageInfo_Taxcode proto.InternalMessageInfo

func (m *Taxcode) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Taxcode) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *Taxcode) GetIsParent() int64 {
	if m != nil {
		return m.IsParent
	}
	return 0
}

func (m *Taxcode) GetCess() string {
	if m != nil {
		return m.Cess
	}
	return ""
}

func (m *Taxcode) GetDutyFree() string {
	if m != nil {
		return m.DutyFree
	}
	return ""
}

func (m *Taxcode) GetDutyFreeDesc() string {
	if m != nil {
		return m.DutyFreeDesc
	}
	return ""
}

func (m *Taxcode) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Taxcode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Taxcode) GetInstruction() string {
	if m != nil {
		return m.Instruction
	}
	return ""
}

func (m *Taxcode) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *Taxcode) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Taxcode) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Taxcode) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ListQuery struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuery) Reset()         { *m = ListQuery{} }
func (m *ListQuery) String() string { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()    {}
func (*ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_d78da315917493c0, []int{1}
}

func (m *ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuery.Unmarshal(m, b)
}
func (m *ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuery.Marshal(b, m, deterministic)
}
func (m *ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuery.Merge(m, src)
}
func (m *ListQuery) XXX_Size() int {
	return xxx_messageInfo_ListQuery.Size(m)
}
func (m *ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuery proto.InternalMessageInfo

func (m *ListQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListQuery) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListQuery) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

type Request struct {
	ListQuery            *ListQuery `protobuf:"bytes,1,opt,name=list_query,json=listQuery,proto3" json:"list_query,omitempty"`
	Taxcode              *Taxcode   `protobuf:"bytes,2,opt,name=Taxcode,proto3" json:"Taxcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d78da315917493c0, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetListQuery() *ListQuery {
	if m != nil {
		return m.ListQuery
	}
	return nil
}

func (m *Request) GetTaxcode() *Taxcode {
	if m != nil {
		return m.Taxcode
	}
	return nil
}

type Response struct {
	Taxcode              *Taxcode   `protobuf:"bytes,1,opt,name=taxcode,proto3" json:"taxcode,omitempty"`
	Taxcodes             []*Taxcode `protobuf:"bytes,2,rep,name=taxcodes,proto3" json:"taxcodes,omitempty"`
	Valid                bool       `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d78da315917493c0, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetTaxcode() *Taxcode {
	if m != nil {
		return m.Taxcode
	}
	return nil
}

func (m *Response) GetTaxcodes() []*Taxcode {
	if m != nil {
		return m.Taxcodes
	}
	return nil
}

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Taxcode)(nil), "taxcode.Taxcode")
	proto.RegisterType((*ListQuery)(nil), "taxcode.ListQuery")
	proto.RegisterType((*Request)(nil), "taxcode.Request")
	proto.RegisterType((*Response)(nil), "taxcode.Response")
}

func init() { proto.RegisterFile("proto/taxcode/taxcode.proto", fileDescriptor_d78da315917493c0) }

var fileDescriptor_d78da315917493c0 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x66, 0xb3, 0xdb, 0x4d, 0x32, 0x29, 0x15, 0x58, 0x08, 0x59, 0x54, 0x48, 0x51, 0xc4, 0xa1,
	0x42, 0xa5, 0x15, 0xcb, 0x13, 0x54, 0x54, 0x20, 0x24, 0x0e, 0x60, 0x95, 0x73, 0x14, 0xe2, 0x01,
	0x2c, 0xd2, 0x38, 0xb5, 0x9d, 0xc2, 0xf2, 0xb6, 0xbc, 0x06, 0x27, 0xe4, 0xb1, 0x93, 0xf6, 0xd0,
	0x43, 0xf7, 0xb4, 0xdf, 0x7c, 0x3f, 0x33, 0xeb, 0x19, 0x05, 0x0e, 0x07, 0xa3, 0x9d, 0x3e, 0x75,
	0xcd, 0xef, 0x56, 0x4b, 0x9c, 0x7e, 0x4f, 0x88, 0x65, 0x69, 0x2c, 0xab, 0xbf, 0x09, 0xa4, 0x17,
	0x01, 0xb3, 0x03, 0x48, 0x94, 0xe4, 0x8b, 0x72, 0x71, 0xb4, 0x14, 0x89, 0x92, 0xec, 0x29, 0xac,
	0x87, 0xc6, 0x60, 0xef, 0x78, 0x42, 0x5c, 0xac, 0xd8, 0x21, 0xe4, 0xca, 0xd6, 0x51, 0x5a, 0x92,
	0x94, 0x29, 0xfb, 0x29, 0x88, 0x0c, 0x56, 0x2d, 0x5a, 0xcb, 0x57, 0xe5, 0xe2, 0x28, 0x17, 0x84,
	0x7d, 0x40, 0x8e, 0x6e, 0x5b, 0x7f, 0x33, 0x88, 0x7c, 0x8f, 0x84, 0xcc, 0x13, 0xef, 0x0c, 0x22,
	0x7b, 0x01, 0x07, 0xb3, 0x58, 0x4b, 0xb4, 0x2d, 0x5f, 0x93, 0x63, 0x7f, 0x72, 0x9c, 0xa3, 0x6d,
	0xa9, 0xad, 0x96, 0xc8, 0x53, 0x1a, 0x47, 0xd8, 0x73, 0x7d, 0x73, 0x89, 0x3c, 0x0b, 0xa3, 0x3c,
	0x66, 0x25, 0x14, 0xaa, 0xb7, 0xce, 0x8c, 0xad, 0x53, 0xba, 0xe7, 0x39, 0x49, 0xb7, 0x29, 0xc6,
	0x21, 0xfd, 0x89, 0xdb, 0x5f, 0xda, 0x48, 0x0e, 0xa4, 0x4e, 0xa5, 0x57, 0xae, 0xd1, 0x58, 0x9f,
	0x2b, 0x82, 0x12, 0x4b, 0xf6, 0x1c, 0xa0, 0x35, 0xd8, 0x38, 0x94, 0x75, 0xe3, 0xf8, 0x3e, 0x89,
	0x79, 0x64, 0xce, 0x9c, 0x97, 0xc7, 0x41, 0x4e, 0xf2, 0xc3, 0x20, 0x47, 0xe6, 0xcc, 0x55, 0x1f,
	0x20, 0xff, 0xa8, 0xac, 0xfb, 0x3c, 0xa2, 0xd9, 0xb2, 0x27, 0xb0, 0xd7, 0xa9, 0x4b, 0xe5, 0xe2,
	0x9e, 0x43, 0xe1, 0x9f, 0x32, 0x34, 0xdf, 0x31, 0x2e, 0x9a, 0xb0, 0xe7, 0xac, 0x36, 0x61, 0xc3,
	0xb9, 0x20, 0x5c, 0xfd, 0x80, 0x54, 0xe0, 0xd5, 0x88, 0xd6, 0xb1, 0xd7, 0x00, 0x9d, 0xb2, 0xae,
	0xbe, 0xf2, 0x6d, 0xa9, 0x5b, 0xb1, 0x61, 0x27, 0xd3, 0x99, 0xe7, 0x81, 0x22, 0xef, 0xe6, 0xd9,
	0x2f, 0xe7, 0x5b, 0xd3, 0xa0, 0x62, 0xf3, 0x68, 0xf6, 0x47, 0x5e, 0x4c, 0x86, 0xea, 0x0f, 0x64,
	0x02, 0xed, 0xa0, 0x7b, 0x8b, 0x3e, 0x17, 0x7d, 0x71, 0xce, 0x1d, 0xb9, 0x48, 0xb0, 0x63, 0xc8,
	0x22, 0xb4, 0x3c, 0x29, 0x97, 0x77, 0x9a, 0x67, 0x87, 0xdf, 0xc6, 0x75, 0xd3, 0x29, 0x49, 0x8f,
	0xcc, 0x44, 0x28, 0x36, 0xff, 0x16, 0x90, 0x5d, 0x4c, 0x96, 0x57, 0xb0, 0xf2, 0x8f, 0x61, 0x37,
	0x6d, 0xe2, 0x06, 0x9e, 0x3d, 0xbe, 0xc5, 0x84, 0x7f, 0x5a, 0x3d, 0x60, 0xc7, 0xb0, 0x7c, 0x8f,
	0xf7, 0x76, 0x9f, 0xc2, 0xfa, 0x2d, 0x9d, 0x71, 0x87, 0xc0, 0x17, 0x3a, 0xec, 0x0e, 0x81, 0x73,
	0xec, 0xf0, 0xde, 0x81, 0xaf, 0x6b, 0xfa, 0x42, 0xdf, 0xfc, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x3c,
	0x93, 0xcf, 0x48, 0xc0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Taxcodes service

type TaxcodesClient interface {
	// 获取国家税收分类编码列表
	List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 根据 唯一 获取国家税收分类编码信息
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 创建国家税收分类编码
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 更新国家税收分类编码
	Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 删除国家税收分类编码
	Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type taxcodesClient struct {
	c           client.Client
	serviceName string
}

func NewTaxcodesClient(serviceName string, c client.Client) TaxcodesClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "taxcode"
	}
	return &taxcodesClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *taxcodesClient) List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Taxcodes.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxcodesClient) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Taxcodes.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxcodesClient) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Taxcodes.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxcodesClient) Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Taxcodes.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxcodesClient) Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Taxcodes.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Taxcodes service

type TaxcodesHandler interface {
	// 获取国家税收分类编码列表
	List(context.Context, *Request, *Response) error
	// 根据 唯一 获取国家税收分类编码信息
	Get(context.Context, *Request, *Response) error
	// 创建国家税收分类编码
	Create(context.Context, *Request, *Response) error
	// 更新国家税收分类编码
	Update(context.Context, *Request, *Response) error
	// 删除国家税收分类编码
	Delete(context.Context, *Request, *Response) error
}

func RegisterTaxcodesHandler(s server.Server, hdlr TaxcodesHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Taxcodes{hdlr}, opts...))
}

type Taxcodes struct {
	TaxcodesHandler
}

func (h *Taxcodes) List(ctx context.Context, in *Request, out *Response) error {
	return h.TaxcodesHandler.List(ctx, in, out)
}

func (h *Taxcodes) Get(ctx context.Context, in *Request, out *Response) error {
	return h.TaxcodesHandler.Get(ctx, in, out)
}

func (h *Taxcodes) Create(ctx context.Context, in *Request, out *Response) error {
	return h.TaxcodesHandler.Create(ctx, in, out)
}

func (h *Taxcodes) Update(ctx context.Context, in *Request, out *Response) error {
	return h.TaxcodesHandler.Update(ctx, in, out)
}

func (h *Taxcodes) Delete(ctx context.Context, in *Request, out *Response) error {
	return h.TaxcodesHandler.Delete(ctx, in, out)
}
